<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator..hAOZq5.App\Entity\Animal' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator..hAOZq5": it references class "App\\Entity\\Animal" but no such service exists.');
