<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator..hAOZq5' shared service.

return $this->privates['.service_locator..hAOZq5'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('animal' => function (): \App\Entity\Animal {
    return ($this->privates['.errored..service_locator..hAOZq5.App\Entity\Animal'] ?? $this->load('getAnimalService.php'));
}));
