<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRoiM3iU\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRoiM3iU/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRoiM3iU.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRoiM3iU\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerRoiM3iU\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'RoiM3iU',
    'container.build_id' => '1672c9d3',
    'container.build_time' => 1536606399,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRoiM3iU');
